server:
  port: 8081

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///data_blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: buzhidao
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # auto create table